CXX = g++
SRC_DIR = src
BIN_DIR = bin
SNAPPY_DIR = snappy-c
INCDIRS = -I ${SNAPPY_DIR}
CXXFLAGS = ${INCDIRS} -ggdb -Wall -std=c++11
OUT = tinylib.a
LDFLAGS = -L ${SNAPPY_DIR} -lsnappyc -L ${BIN_DIR} -l:${OUT}

SRC_CLIENT = ${SRC_DIR}/client.cpp
SRC_SERVER = ${SRC_DIR}/server.cpp
SRC_APP = ${SRC_DIR}/app.cpp

OBJ_DIR = ${BIN_DIR}/obj
OBJ_CLIENT = ${OBJ_DIR}/client.o
OBJ_SERVER = ${OBJ_DIR}/server.o
OBJ_APP = ${OBJ_DIR}/app.o

all: snappy ${OUT} server app

${OBJ_DIR}/%.o: ${SRC_DIR}/%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

${OUT}: ${OBJ_CLIENT}
	ar rcs ${BIN_DIR}/${OUT} ${OBJ_CLIENT}

server: ${OBJ_SERVER}
	$(CXX) $(CXXFLAGS) ${SRC_SERVER} -o ${BIN_DIR}/server ${LDFLAGS}

app: ${OBJ_APP} ${OUT}
	$(CXX) $(CXXFLAGS) ${SRC_APP} -o ${BIN_DIR}/app ${LDFLAGS}

snappy:
	$(MAKE) -C ${SNAPPY_DIR}

clean:
	-@rm ${OBJ_DIR}/*.o ${BIN_DIR}/*.a ${BIN_DIR}/server ${BIN_DIR}/app;
	@echo Cleaned!
